### ISSUE TITLE
Homing Example doesn't work on concert_description

### ISSUE THREAD

**Issue by manuelvogel12** [ADVRHumanoids/concert_description#13]
Changing the modular.yaml from 
```
  homing:
    thread: rt_main
    type: homing
    params:
      time: { value: 5.0, type: double }
```
to 
```
  homing:
    thread: rt_main
    type: homing_example
    params:
      time: { value: 5.0, type: double }
```
results in the following errors:
```
              /xbot2: [err ][J_wheel_A] [J_wheel_A] resource 'Position' undefined
              /xbot2: [err ][robot_homing] [J_wheel_A] failed to acquire 'Position' control mode
              /xbot2: [info][rt_main] xbot2 thread 'rt_main' transits to state 'Run' 
              /xbot2: [err ][J_wheel_B] [J_wheel_B] resource 'Position' undefined
              /xbot2: [err ][robot_homing] [J_wheel_B] failed to acquire 'Position' control mode
              /xbot2: [err ][J_wheel_C] [J_wheel_C] resource 'Position' undefined
              /xbot2: [err ][robot_homing] [J_wheel_C] failed to acquire 'Position' control mode
              /xbot2: [err ][J_wheel_D] [J_wheel_D] resource 'Position' undefined
              /xbot2: [err ][robot_homing] [J_wheel_D] failed to acquire 'Position' control mode

```
I guess it is similar to #9, and caused by  this line :

```
_robot->setControlMode(ControlMode::Position());
```
The same also happens in self written C++ Plugins. And I tried to change Control Mode to ControlMode::Velocity(), but then no errors would be thrown, but the robot still doesn't move.
